Lukee csv -tiedostot kansiosta c:\apu 

Vaatii SQL Server tietokannassa valmiina FinalProject nimisen tietokannan

Muokkaus tarpeen mukaan

HUOM! Vuosilta 2019 ei keskinopeus-dataa -> 0

In [96]:
import pandas as pd

In [97]:
#luetaan 2019 data
df = pd.read_csv('C:\\apu\\liikennemaara_h_2019-01-01-2019-12-31_viikinmaki.csv',sep =';',encoding= 'utf-8',header = 0)
df

,pistetunnus,sijainti,pvm,suunta,suuntaselite,kaista,jaottelu,ajoneuvoluokka,00_01,01_02,...,15_16,16_17,17_18,18_19,19_20,20_21,21_22,22_23,23_24,yhteensa
0,154,vt4_Viikinmäki,20190101,1,Lahti,*,Ajoneuvoluokka,HA - PA,666,559,...,737,875,702,627,537,592,445,236,151,10356
1,154,vt4_Viikinmäki,20190101,2,Helsinki,*,Ajoneuvoluokka,HA - PA,253,277,...,941,949,877,827,697,525,368,253,161,10515
2,154,vt4_Viikinmäki,20190102,1,Lahti,*,Ajoneuvoluokka,HA - PA,113,66,...,2487,2250,1494,1152,835,723,574,422,192,18212
3,154,vt4_Viikinmäki,20190102,2,Helsinki,*,Ajoneuvoluokka,HA - PA,69,46,...,1174,1256,1075,893,769,659,425,254,170,20162
4,154,vt4_Viikinmäki,20190103,1,Lahti,*,Ajoneuvoluokka,HA - PA,130,118,...,2540,2491,1751,1191,945,879,836,434,174,20349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,154,vt4_Viikinmäki,20191229,2,Helsinki,*,Ajoneuvoluokka,HA - PA,193,133,...,1573,1381,1156,1062,875,653,397,243,153,14185
726,154,vt4_Viikinmäki,20191230,1,Lahti,*,Ajoneuvoluokka,HA - PA,132,114,...,2350,1907,1308,1030,870,748,926,361,205,18336
727,154,vt4_Viikinmäki,20191230,2,Helsinki,*,Ajoneuvoluokka,HA - PA,105,72,...,1275,1282,1308,877,801,638,454,279,158,19650
728,154,vt4_Viikinmäki,20191231,1,Lahti,*,Ajoneuvoluokka,HA - PA,169,113,...,1711,1362,927,735,547,463,456,363,299,15126
729,154,vt4_Viikinmäki,20191231,2,Helsinki,*,Ajoneuvoluokka,HA - PA,118,53,...,1223,1134,940,797,620,554,473,614,699,17512

In [98]:
dftapiola19 = pd.read_csv('C:\\apu\\liikennemaara_h_2019-01-01-2019-12-31_tapiola.csv',sep =';',encoding= 'utf-8',header = 0)
dftapiola19

,pistetunnus,sijainti,pvm,suunta,suuntaselite,kaista,jaottelu,ajoneuvoluokka,00_01,01_02,...,15_16,16_17,17_18,18_19,19_20,20_21,21_22,22_23,23_24,yhteensa
0,118,st101_Espoo_Keilaniemi,20191201,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,156,97,...,885,924,754,651,531,301,377,227,88,9374
1,118,st101_Espoo_Keilaniemi,20191201,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,142,90,...,930,750,669,561,487,447,269,141,99,8506
2,118,st101_Espoo_Keilaniemi,20191202,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,87,65,...,1148,1018,948,771,579,509,463,132,84,17175
3,118,st101_Espoo_Keilaniemi,20191202,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,59,26,...,1859,2293,1781,1124,741,603,390,191,108,16987
4,118,st101_Espoo_Keilaniemi,20191203,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,56,19,...,1187,1110,1076,884,628,534,433,197,90,17603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,118,st101_Espoo_Keilaniemi,20191229,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,99,59,...,687,607,525,489,371,365,211,132,89,6405
58,118,st101_Espoo_Keilaniemi,20191230,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,70,35,...,926,906,695,604,447,336,369,149,94,11740
59,118,st101_Espoo_Keilaniemi,20191230,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,53,32,...,1300,1392,991,708,470,373,310,146,89,11425
60,118,st101_Espoo_Keilaniemi,20191231,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,53,20,...,764,618,522,460,311,226,198,186,186,9656
61,118,st101_Espoo_Keilaniemi,20191231,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,44,33,...,1099,912,638,495,349,232,214,212,206,9544

In [100]:
dfpakkala19 = pd.read_csv('C:\\apu\\liikennemaara_h_2019-01-01-2019-12-31_pakkala.csv',sep =';',encoding= 'utf-8',header = 0)
dfpakkala19

,pistetunnus,sijainti,pvm,suunta,suuntaselite,kaista,jaottelu,ajoneuvoluokka,00_01,01_02,...,15_16,16_17,17_18,18_19,19_20,20_21,21_22,22_23,23_24,yhteensa
0,169,kt50_Pakkala,20190101,1,Vantaa,*,Ajoneuvoluokka,HA - PA,235,269,...,1040,1023,880,751,570,448,332,237,143,10476
1,169,kt50_Pakkala,20190101,2,Espoo,*,Ajoneuvoluokka,HA - PA,266,295,...,1158,1176,1112,865,725,619,449,303,273,11938
2,169,kt50_Pakkala,20190102,1,Vantaa,*,Ajoneuvoluokka,HA - PA,81,65,...,2188,1970,1420,1036,717,566,441,336,174,20833
3,169,kt50_Pakkala,20190102,2,Espoo,*,Ajoneuvoluokka,HA - PA,153,102,...,2251,1872,1675,1248,1020,819,681,443,282,24355
4,169,kt50_Pakkala,20190103,1,Vantaa,*,Ajoneuvoluokka,HA - PA,83,65,...,2290,2223,1652,1139,756,646,467,339,158,22645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,169,kt50_Pakkala,20191229,2,Espoo,*,Ajoneuvoluokka,HA - PA,254,135,...,1609,1574,1523,1310,1051,828,595,418,334,15899
726,169,kt50_Pakkala,20191230,1,Vantaa,*,Ajoneuvoluokka,HA - PA,100,73,...,2142,1894,1420,1056,710,557,489,358,180,20966
727,169,kt50_Pakkala,20191230,2,Espoo,*,Ajoneuvoluokka,HA - PA,219,102,...,2317,2147,1754,1278,1180,921,790,512,355,24757
728,169,kt50_Pakkala,20191231,1,Vantaa,*,Ajoneuvoluokka,HA - PA,116,84,...,1798,1433,1149,867,563,399,378,337,266,17984
729,169,kt50_Pakkala,20191231,2,Espoo,*,Ajoneuvoluokka,HA - PA,184,117,...,2003,1669,1337,1027,699,549,379,376,275,21056

In [102]:
#yhdistetään kaikki 2019 df:t
df = pd.concat([df, dftapiola19, dfpakkala19])
df

,pistetunnus,sijainti,pvm,suunta,suuntaselite,kaista,jaottelu,ajoneuvoluokka,00_01,01_02,...,15_16,16_17,17_18,18_19,19_20,20_21,21_22,22_23,23_24,yhteensa
0,154,vt4_Viikinmäki,20190101,1,Lahti,*,Ajoneuvoluokka,HA - PA,666,559,...,737,875,702,627,537,592,445,236,151,10356
1,154,vt4_Viikinmäki,20190101,2,Helsinki,*,Ajoneuvoluokka,HA - PA,253,277,...,941,949,877,827,697,525,368,253,161,10515
2,154,vt4_Viikinmäki,20190102,1,Lahti,*,Ajoneuvoluokka,HA - PA,113,66,...,2487,2250,1494,1152,835,723,574,422,192,18212
3,154,vt4_Viikinmäki,20190102,2,Helsinki,*,Ajoneuvoluokka,HA - PA,69,46,...,1174,1256,1075,893,769,659,425,254,170,20162
4,154,vt4_Viikinmäki,20190103,1,Lahti,*,Ajoneuvoluokka,HA - PA,130,118,...,2540,2491,1751,1191,945,879,836,434,174,20349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,169,kt50_Pakkala,20191229,2,Espoo,*,Ajoneuvoluokka,HA - PA,254,135,...,1609,1574,1523,1310,1051,828,595,418,334,15899
726,169,kt50_Pakkala,20191230,1,Vantaa,*,Ajoneuvoluokka,HA - PA,100,73,...,2142,1894,1420,1056,710,557,489,358,180,20966
727,169,kt50_Pakkala,20191230,2,Espoo,*,Ajoneuvoluokka,HA - PA,219,102,...,2317,2147,1754,1278,1180,921,790,512,355,24757
728,169,kt50_Pakkala,20191231,1,Vantaa,*,Ajoneuvoluokka,HA - PA,116,84,...,1798,1433,1149,867,563,399,378,337,266,17984
729,169,kt50_Pakkala,20191231,2,Espoo,*,Ajoneuvoluokka,HA - PA,184,117,...,2003,1669,1337,1027,699,549,379,376,275,21056

In [103]:
df = df.drop(['kaista','jaottelu','sijainti','ajoneuvoluokka'],axis=1)

In [104]:
columns = df.columns
tila = columns[0:4]
tila2 = columns[4:-1]

In [105]:
df_unpivot = pd.melt(df, id_vars=tila, value_vars=tila2)

In [106]:
df_unpivot.rename(columns = {'value':'Määrä'},inplace=True)
df_unpivot.rename(columns = {'variable':'klo'},inplace=True)

In [107]:
df_unpivot[['klo', 'poisto']] = df_unpivot['klo'].str.split('_', n=1, expand=True)
df = df_unpivot.drop(['poisto'],axis =1)

In [108]:
#lisätään keskinopeus sarake ja muutetaan järjestystä
df['keskinopeus'] = 0
df.rename(columns = {'pistetunnus':'sijainti'},inplace=True)
df19 = df[['sijainti','pvm', 'klo','suunta','suuntaselite', 'Määrä','keskinopeus']]
df19

       sijainti       pvm klo  suunta suuntaselite  Määrä  keskinopeus
0           154  20190101  00       1        Lahti    666            0
1           154  20190101  00       2     Helsinki    253            0
2           154  20190102  00       1        Lahti    113            0
3           154  20190102  00       2     Helsinki     69            0
4           154  20190103  00       1        Lahti    130            0
...         ...       ...  ..     ...          ...    ...          ...
36523       169  20191229  23       2        Espoo    334            0
36524       169  20191230  23       1       Vantaa    180            0
36525       169  20191230  23       2        Espoo    355            0
36526       169  20191231  23       1       Vantaa    266            0
36527       169  20191231  23       2        Espoo    275            0

[36528 rows x 7 columns]

In [109]:
#luetaan 2020-22 data
df4 = pd.read_csv('C:\\apu\\keskinopeus_h_2020-01-01-2023-03-31_viikinmaki.csv', sep=';')

In [110]:
df4

,pistetunnus,sijainti,pvm,klo,suunta,suuntaselite,nopeusrajoitus,kaikki,kevyet,raskaat,keskinopeus_kaikki,keskinopeus_kevyet,keskinopeus_raskaat
0,154,vt4_Viikinmäki,20200101,0,1,Lahti,100/100,762,736,26.0,88.3,88.4,85.5
1,154,vt4_Viikinmäki,20200101,0,2,Helsinki,100/100,323,296,27.0,91.6,92.7,79.6
2,154,vt4_Viikinmäki,20200101,1,1,Lahti,100/100,664,629,35.0,86.6,86.8,82.7
3,154,vt4_Viikinmäki,20200101,1,2,Helsinki,100/100,363,337,26.0,91.2,92.1,79.3
4,154,vt4_Viikinmäki,20200101,2,1,Lahti,100/100,412,382,30.0,87.9,88.2,83.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56369,154,vt4_Viikinmäki,20230331,21,2,Helsinki,100/100,590,556,34.0,93.4,93.9,84.2
56370,154,vt4_Viikinmäki,20230331,22,1,Lahti,100/100,724,682,42.0,96.8,97.5,85.5
56371,154,vt4_Viikinmäki,20230331,22,2,Helsinki,100/100,457,431,26.0,93.6,94.2,83.8
56372,154,vt4_Viikinmäki,20230331,23,1,Lahti,100/100,504,472,32.0,95.4,96.0,86.7
56373,154,vt4_Viikinmäki,20230331,23,2,Helsinki,100/100,282,248,34.0,92.6,93.7,84.6

In [111]:
#Muokataan dataframea
df20_22 = df4.drop(['sijainti','nopeusrajoitus','kaikki', 'raskaat','kaikki','keskinopeus_kaikki','keskinopeus_raskaat'], axis=1)
df20_22.rename(columns = {'pistetunnus':'sijainti'},inplace=True)
df20_22.rename(columns = {'kevyet':'Määrä'},inplace=True)
df20_22.rename(columns = {'keskinopeus_kevyet':'keskinopeus'},inplace=True)
df20_22

       sijainti       pvm  klo  suunta suuntaselite  Määrä  keskinopeus
0           154  20200101    0       1        Lahti    736         88.4
1           154  20200101    0       2     Helsinki    296         92.7
2           154  20200101    1       1        Lahti    629         86.8
3           154  20200101    1       2     Helsinki    337         92.1
4           154  20200101    2       1        Lahti    382         88.2
...         ...       ...  ...     ...          ...    ...          ...
56369       154  20230331   21       2     Helsinki    556         93.9
56370       154  20230331   22       1        Lahti    682         97.5
56371       154  20230331   22       2     Helsinki    431         94.2
56372       154  20230331   23       1        Lahti    472         96.0
56373       154  20230331   23       2     Helsinki    248         93.7

[56374 rows x 7 columns]

In [119]:
#luetaan tapiolan data 20-23
dftapiola20_23 = pd.read_csv('C:\\apu\\keskinopeus_h_2020-01-01-2023-03-31_tapiola.csv', sep=';')
dftapiola20_23

,pistetunnus,sijainti,pvm,klo,suunta,suuntaselite,nopeusrajoitus,kaikki,kevyet,raskaat,keskinopeus_kaikki,keskinopeus_kevyet,keskinopeus_raskaat
0,118,st101_Espoo_Keilaniemi,20200101,0,1,Itäkeskus,60/60,317,315.0,2.0,57.8,57.8,64.5
1,118,st101_Espoo_Keilaniemi,20200101,0,2,Länsiväylä,60/60,199,198.0,1.0,68.1,68.1,70.0
2,118,st101_Espoo_Keilaniemi,20200101,1,1,Itäkeskus,60/60,293,289.0,4.0,57.5,57.5,55.5
3,118,st101_Espoo_Keilaniemi,20200101,1,2,Länsiväylä,60/60,220,217.0,3.0,66.5,66.4,72.0
4,118,st101_Espoo_Keilaniemi,20200101,2,1,Itäkeskus,60/60,152,151.0,1.0,57.8,57.9,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56873,118,st101_Espoo_Keilaniemi,20230331,21,2,Länsiväylä,60/60,425,409.0,16.0,69.0,69.1,66.1
56874,118,st101_Espoo_Keilaniemi,20230331,22,1,Itäkeskus,60/60,317,314.0,3.0,61.9,61.9,61.3
56875,118,st101_Espoo_Keilaniemi,20230331,22,2,Länsiväylä,60/60,361,357.0,4.0,70.3,70.2,75.3
56876,118,st101_Espoo_Keilaniemi,20230331,23,1,Itäkeskus,60/60,237,233.0,4.0,62.5,62.5,58.3
56877,118,st101_Espoo_Keilaniemi,20230331,23,2,Länsiväylä,60/60,260,258.0,2.0,71.1,71.0,73.5

In [118]:
#luetaan pakkalan data 20-23
dfpakkala20_23 = pd.read_csv('C:\\apu\\keskinopeus_h_2020-01-01-2023-03-31_pakkala.csv', sep=';')
dfpakkala20_23

,pistetunnus,sijainti,pvm,klo,suunta,suuntaselite,nopeusrajoitus,kaikki,kevyet,raskaat,keskinopeus_kaikki,keskinopeus_kevyet,keskinopeus_raskaat
0,169,kt50_Pakkala,20200101,0,1,Vantaa,80/80,310,290.0,20.0,82.1,82.2,81.8
1,169,kt50_Pakkala,20200101,0,2,Espoo,80/80,349,338.0,11.0,82.2,82.2,80.2
2,169,kt50_Pakkala,20200101,1,1,Vantaa,80/80,335,323.0,12.0,82.7,82.6,85.7
3,169,kt50_Pakkala,20200101,1,2,Espoo,80/80,324,312.0,12.0,83.5,83.6,81.2
4,169,kt50_Pakkala,20200101,2,1,Vantaa,80/80,240,232.0,8.0,81.9,82.0,79.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56407,169,kt50_Pakkala,20230331,21,2,Espoo,80/80,639,614.0,25.0,86.1,86.2,84.1
56408,169,kt50_Pakkala,20230331,22,1,Vantaa,80/80,544,501.0,43.0,83.3,83.5,79.9
56409,169,kt50_Pakkala,20230331,22,2,Espoo,80/80,516,495.0,21.0,86.4,86.5,82.0
56410,169,kt50_Pakkala,20230331,23,1,Vantaa,80/80,323,283.0,40.0,83.4,83.4,83.1
56411,169,kt50_Pakkala,20230331,23,2,Espoo,80/80,319,297.0,22.0,85.8,86.1,81.5

In [121]:
#yhdistetään tapiola ja pakkala 20-23
dftp20_23 = pd.concat([dftapiola20_23, dfpakkala20_23], ignore_index=True)
dftp20_23

,pistetunnus,sijainti,pvm,klo,suunta,suuntaselite,nopeusrajoitus,kaikki,kevyet,raskaat,keskinopeus_kaikki,keskinopeus_kevyet,keskinopeus_raskaat
0,118,st101_Espoo_Keilaniemi,20200101,0,1,Itäkeskus,60/60,317,315.0,2.0,57.8,57.8,64.5
1,118,st101_Espoo_Keilaniemi,20200101,0,2,Länsiväylä,60/60,199,198.0,1.0,68.1,68.1,70.0
2,118,st101_Espoo_Keilaniemi,20200101,1,1,Itäkeskus,60/60,293,289.0,4.0,57.5,57.5,55.5
3,118,st101_Espoo_Keilaniemi,20200101,1,2,Länsiväylä,60/60,220,217.0,3.0,66.5,66.4,72.0
4,118,st101_Espoo_Keilaniemi,20200101,2,1,Itäkeskus,60/60,152,151.0,1.0,57.8,57.9,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113285,169,kt50_Pakkala,20230331,21,2,Espoo,80/80,639,614.0,25.0,86.1,86.2,84.1
113286,169,kt50_Pakkala,20230331,22,1,Vantaa,80/80,544,501.0,43.0,83.3,83.5,79.9
113287,169,kt50_Pakkala,20230331,22,2,Espoo,80/80,516,495.0,21.0,86.4,86.5,82.0
113288,169,kt50_Pakkala,20230331,23,1,Vantaa,80/80,323,283.0,40.0,83.4,83.4,83.1
113289,169,kt50_Pakkala,20230331,23,2,Espoo,80/80,319,297.0,22.0,85.8,86.1,81.5

In [122]:
#Muokataan tapiola&pakkala dataframea
dftp20_23 = dftp20_23.drop(['sijainti','nopeusrajoitus','kaikki', 'raskaat','keskinopeus_kaikki','keskinopeus_raskaat'], axis=1)
dftp20_23.rename(columns = {'pistetunnus':'sijainti'},inplace=True)
dftp20_23.rename(columns = {'kevyet':'Määrä'},inplace=True)
dftp20_23.rename(columns = {'keskinopeus_kevyet':'keskinopeus'},inplace=True)
dftp20_23

        sijainti       pvm  klo  suunta suuntaselite  Määrä  keskinopeus
0            118  20200101    0       1    Itäkeskus  315.0         57.8
1            118  20200101    0       2   Länsiväylä  198.0         68.1
2            118  20200101    1       1    Itäkeskus  289.0         57.5
3            118  20200101    1       2   Länsiväylä  217.0         66.4
4            118  20200101    2       1    Itäkeskus  151.0         57.9
...          ...       ...  ...     ...          ...    ...          ...
113285       169  20230331   21       2        Espoo  614.0         86.2
113286       169  20230331   22       1       Vantaa  501.0         83.5
113287       169  20230331   22       2        Espoo  495.0         86.5
113288       169  20230331   23       1       Vantaa  283.0         83.4
113289       169  20230331   23       2        Espoo  297.0         86.1

[113290 rows x 7 columns]

In [123]:
# poistetaan null rivit
dftp20_23.dropna(inplace=True, axis=0)

# rivien määrän null poiston jälkeen
row_count_tp = len(dftp20_23)
print(row_count_tp)

dftp20_23.head(1)

113286

   sijainti       pvm  klo  suunta suuntaselite  Määrä  keskinopeus
0       118  20200101    0       1    Itäkeskus  315.0         57.8

In [125]:
#muutetaan Määrä sarakkeen datatyyppi float to int
dftp20_23['Määrä'] = dftp20_23['Määrä'].astype(int)
dftp20_23.dtypes

sijainti          int64
pvm               int64
klo               int64
suunta            int64
suuntaselite     object
Määrä             int32
keskinopeus     float64
dtype: object

In [126]:
#Yhdistetään 2019 ja kumpula 20_22 ja tapiola&pakkala 20_23
dfLiikenne = pd.concat([df19, df20_22, dftp20_23], ignore_index=True)
dfLiikenne

        sijainti       pvm klo  suunta suuntaselite  Määrä  keskinopeus
0            154  20190101  00       1        Lahti    666          0.0
1            154  20190101  00       2     Helsinki    253          0.0
2            154  20190102  00       1        Lahti    113          0.0
3            154  20190102  00       2     Helsinki     69          0.0
4            154  20190103  00       1        Lahti    130          0.0
...          ...       ...  ..     ...          ...    ...          ...
206183       169  20230331  21       2        Espoo    614         86.2
206184       169  20230331  22       1       Vantaa    501         83.5
206185       169  20230331  22       2        Espoo    495         86.5
206186       169  20230331  23       1       Vantaa    283         83.4
206187       169  20230331  23       2        Espoo    297         86.1

[206188 rows x 7 columns]

In [127]:
#csv:ksi
dfLiikenne.to_csv('c:\\apu\\Liikennemaarat_nopeudet_2019_23.csv')

In [130]:
# FactLiikenne taulun luonti tietokantaan
import pyodbc

server = 'localhost'
database = 'FinalProject'
username = 'sa'
password = 'Password1'
cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)


cnxn.execute("Create table FactLiikenne (Liikenne_id int IDENTITY(1,1) Primary Key, sijainti varchar(50), pvm int, klo int, suunta int, suuntaselite varchar(20), maara int, keskinopeus float)") 
cnxn.commit()
cnxn.close()

In [131]:
#tiedot tietokantaan
import pyodbc
server = 'localhost'
database = 'FinalProject'
username = 'sa'
password = 'Password1'
cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()

d = pd.DataFrame(dfLiikenne)

for index, row in d.iterrows():
    cursor.execute("INSERT INTO FactLiikenne values (?,?,?,?,?,?,?)",row['sijainti'],row['pvm'],row['klo'],row['suunta'],row['suuntaselite'],row['Määrä'],row['keskinopeus']) 
cnxn.commit()
cnxn.close()