Lukee csv -tiedostot kansiosta c:\apu 

Vaatii SQL Server tietokannassa valmiina FinalProject nimisen tietokannan

Muokkaus tarpeen mukaan

HUOM! Vuosilta 2019 ei keskinopeus-dataa -> 0

In [65]:
import pandas as pd

In [66]:
#luetaan 2019 data
df = pd.read_csv('C:\\apu\\liikennemaara_h_2019-01-01-2019-12-31_viikinmaki.csv',sep =';',encoding= 'utf-8',header = 0)
df

,pistetunnus,sijainti,pvm,suunta,suuntaselite,kaista,jaottelu,ajoneuvoluokka,00_01,01_02,...,15_16,16_17,17_18,18_19,19_20,20_21,21_22,22_23,23_24,yhteensa
0,154,vt4_Viikinmäki,20190101,1,Lahti,*,Ajoneuvoluokka,HA - PA,666,559,...,737,875,702,627,537,592,445,236,151,10356
1,154,vt4_Viikinmäki,20190101,2,Helsinki,*,Ajoneuvoluokka,HA - PA,253,277,...,941,949,877,827,697,525,368,253,161,10515
2,154,vt4_Viikinmäki,20190102,1,Lahti,*,Ajoneuvoluokka,HA - PA,113,66,...,2487,2250,1494,1152,835,723,574,422,192,18212
3,154,vt4_Viikinmäki,20190102,2,Helsinki,*,Ajoneuvoluokka,HA - PA,69,46,...,1174,1256,1075,893,769,659,425,254,170,20162
4,154,vt4_Viikinmäki,20190103,1,Lahti,*,Ajoneuvoluokka,HA - PA,130,118,...,2540,2491,1751,1191,945,879,836,434,174,20349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,154,vt4_Viikinmäki,20191229,2,Helsinki,*,Ajoneuvoluokka,HA - PA,193,133,...,1573,1381,1156,1062,875,653,397,243,153,14185
726,154,vt4_Viikinmäki,20191230,1,Lahti,*,Ajoneuvoluokka,HA - PA,132,114,...,2350,1907,1308,1030,870,748,926,361,205,18336
727,154,vt4_Viikinmäki,20191230,2,Helsinki,*,Ajoneuvoluokka,HA - PA,105,72,...,1275,1282,1308,877,801,638,454,279,158,19650
728,154,vt4_Viikinmäki,20191231,1,Lahti,*,Ajoneuvoluokka,HA - PA,169,113,...,1711,1362,927,735,547,463,456,363,299,15126
729,154,vt4_Viikinmäki,20191231,2,Helsinki,*,Ajoneuvoluokka,HA - PA,118,53,...,1223,1134,940,797,620,554,473,614,699,17512

In [67]:
dftapiola19 = pd.read_csv('C:\\apu\\liikennemaara_h_2019-01-01-2019-12-31_tapiola.csv',sep =';',encoding= 'utf-8',header = 0)
dftapiola19

,pistetunnus,sijainti,pvm,suunta,suuntaselite,kaista,jaottelu,ajoneuvoluokka,00_01,01_02,...,15_16,16_17,17_18,18_19,19_20,20_21,21_22,22_23,23_24,yhteensa
0,118,st101_Espoo_Keilaniemi,20191201,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,156,97,...,885,924,754,651,531,301,377,227,88,9374
1,118,st101_Espoo_Keilaniemi,20191201,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,142,90,...,930,750,669,561,487,447,269,141,99,8506
2,118,st101_Espoo_Keilaniemi,20191202,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,87,65,...,1148,1018,948,771,579,509,463,132,84,17175
3,118,st101_Espoo_Keilaniemi,20191202,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,59,26,...,1859,2293,1781,1124,741,603,390,191,108,16987
4,118,st101_Espoo_Keilaniemi,20191203,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,56,19,...,1187,1110,1076,884,628,534,433,197,90,17603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,118,st101_Espoo_Keilaniemi,20191229,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,99,59,...,687,607,525,489,371,365,211,132,89,6405
58,118,st101_Espoo_Keilaniemi,20191230,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,70,35,...,926,906,695,604,447,336,369,149,94,11740
59,118,st101_Espoo_Keilaniemi,20191230,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,53,32,...,1300,1392,991,708,470,373,310,146,89,11425
60,118,st101_Espoo_Keilaniemi,20191231,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,53,20,...,764,618,522,460,311,226,198,186,186,9656
61,118,st101_Espoo_Keilaniemi,20191231,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,44,33,...,1099,912,638,495,349,232,214,212,206,9544

In [68]:
df = pd.concat([df, dftapiola19])
df

,pistetunnus,sijainti,pvm,suunta,suuntaselite,kaista,jaottelu,ajoneuvoluokka,00_01,01_02,...,15_16,16_17,17_18,18_19,19_20,20_21,21_22,22_23,23_24,yhteensa
0,154,vt4_Viikinmäki,20190101,1,Lahti,*,Ajoneuvoluokka,HA - PA,666,559,...,737,875,702,627,537,592,445,236,151,10356
1,154,vt4_Viikinmäki,20190101,2,Helsinki,*,Ajoneuvoluokka,HA - PA,253,277,...,941,949,877,827,697,525,368,253,161,10515
2,154,vt4_Viikinmäki,20190102,1,Lahti,*,Ajoneuvoluokka,HA - PA,113,66,...,2487,2250,1494,1152,835,723,574,422,192,18212
3,154,vt4_Viikinmäki,20190102,2,Helsinki,*,Ajoneuvoluokka,HA - PA,69,46,...,1174,1256,1075,893,769,659,425,254,170,20162
4,154,vt4_Viikinmäki,20190103,1,Lahti,*,Ajoneuvoluokka,HA - PA,130,118,...,2540,2491,1751,1191,945,879,836,434,174,20349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,118,st101_Espoo_Keilaniemi,20191229,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,99,59,...,687,607,525,489,371,365,211,132,89,6405
58,118,st101_Espoo_Keilaniemi,20191230,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,70,35,...,926,906,695,604,447,336,369,149,94,11740
59,118,st101_Espoo_Keilaniemi,20191230,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,53,32,...,1300,1392,991,708,470,373,310,146,89,11425
60,118,st101_Espoo_Keilaniemi,20191231,1,Itäkeskus,*,Ajoneuvoluokka,HA - PA,53,20,...,764,618,522,460,311,226,198,186,186,9656
61,118,st101_Espoo_Keilaniemi,20191231,2,Länsiväylä,*,Ajoneuvoluokka,HA - PA,44,33,...,1099,912,638,495,349,232,214,212,206,9544

In [69]:
df = df.drop(['kaista','jaottelu','sijainti','ajoneuvoluokka'],axis=1)

In [70]:
columns = df.columns
tila = columns[0:4]
tila2 = columns[4:-1]

In [71]:
df_unpivot = pd.melt(df, id_vars=tila, value_vars=tila2)

In [72]:
df_unpivot.rename(columns = {'value':'Määrä'},inplace=True)
df_unpivot.rename(columns = {'variable':'klo'},inplace=True)

In [73]:
df_unpivot[['klo', 'poisto']] = df_unpivot['klo'].str.split('_', n=1, expand=True)
df = df_unpivot.drop(['poisto'],axis =1)

In [74]:
#lisätään keskinopeus sarake ja muutetaan järjestystä
df['keskinopeus'] = 0
df.rename(columns = {'pistetunnus':'sijainti'},inplace=True)
df19 = df[['sijainti','pvm', 'klo','suunta','suuntaselite', 'Määrä','keskinopeus']]
df19

       sijainti       pvm klo  suunta suuntaselite  Määrä  keskinopeus
0           154  20190101  00       1        Lahti    666            0
1           154  20190101  00       2     Helsinki    253            0
2           154  20190102  00       1        Lahti    113            0
3           154  20190102  00       2     Helsinki     69            0
4           154  20190103  00       1        Lahti    130            0
...         ...       ...  ..     ...          ...    ...          ...
19003       118  20191229  23       2   Länsiväylä     89            0
19004       118  20191230  23       1    Itäkeskus     94            0
19005       118  20191230  23       2   Länsiväylä     89            0
19006       118  20191231  23       1    Itäkeskus    186            0
19007       118  20191231  23       2   Länsiväylä    206            0

[19008 rows x 7 columns]

In [75]:
#luetaan 2020-22 data
df4 = pd.read_csv('C:\\apu\\keskinopeus_h_2020-01-01-2023-03-31_viikinmaki.csv', sep=';')

In [76]:
df4

,pistetunnus,sijainti,pvm,klo,suunta,suuntaselite,nopeusrajoitus,kaikki,kevyet,raskaat,keskinopeus_kaikki,keskinopeus_kevyet,keskinopeus_raskaat
0,154,vt4_Viikinmäki,20200101,0,1,Lahti,100/100,762,736,26.0,88.3,88.4,85.5
1,154,vt4_Viikinmäki,20200101,0,2,Helsinki,100/100,323,296,27.0,91.6,92.7,79.6
2,154,vt4_Viikinmäki,20200101,1,1,Lahti,100/100,664,629,35.0,86.6,86.8,82.7
3,154,vt4_Viikinmäki,20200101,1,2,Helsinki,100/100,363,337,26.0,91.2,92.1,79.3
4,154,vt4_Viikinmäki,20200101,2,1,Lahti,100/100,412,382,30.0,87.9,88.2,83.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56369,154,vt4_Viikinmäki,20230331,21,2,Helsinki,100/100,590,556,34.0,93.4,93.9,84.2
56370,154,vt4_Viikinmäki,20230331,22,1,Lahti,100/100,724,682,42.0,96.8,97.5,85.5
56371,154,vt4_Viikinmäki,20230331,22,2,Helsinki,100/100,457,431,26.0,93.6,94.2,83.8
56372,154,vt4_Viikinmäki,20230331,23,1,Lahti,100/100,504,472,32.0,95.4,96.0,86.7
56373,154,vt4_Viikinmäki,20230331,23,2,Helsinki,100/100,282,248,34.0,92.6,93.7,84.6

In [82]:
#Muokataan dataframea
df20_22 = df4.drop(['sijainti','nopeusrajoitus','kaikki', 'raskaat','kaikki','keskinopeus_kaikki','keskinopeus_raskaat'], axis=1)
df20_22.rename(columns = {'pistetunnus':'sijainti'},inplace=True)
df20_22.rename(columns = {'kevyet':'Määrä'},inplace=True)
df20_22.rename(columns = {'keskinopeus_kevyet':'keskinopeus'},inplace=True)
df20_22

       sijainti       pvm  klo  suunta suuntaselite  Määrä  keskinopeus
0           154  20200101    0       1        Lahti    736         88.4
1           154  20200101    0       2     Helsinki    296         92.7
2           154  20200101    1       1        Lahti    629         86.8
3           154  20200101    1       2     Helsinki    337         92.1
4           154  20200101    2       1        Lahti    382         88.2
...         ...       ...  ...     ...          ...    ...          ...
56369       154  20230331   21       2     Helsinki    556         93.9
56370       154  20230331   22       1        Lahti    682         97.5
56371       154  20230331   22       2     Helsinki    431         94.2
56372       154  20230331   23       1        Lahti    472         96.0
56373       154  20230331   23       2     Helsinki    248         93.7

[56374 rows x 7 columns]

In [87]:
dftapiola20_22 = pd.read_csv('C:\\apu\\keskinopeus_h_2020-01-01-2023-03-31_tapiola.csv', sep=';')
dftapiola20_22

,pistetunnus,sijainti,pvm,klo,suunta,suuntaselite,nopeusrajoitus,kaikki,kevyet,raskaat,keskinopeus_kaikki,keskinopeus_kevyet,keskinopeus_raskaat
0,118,st101_Espoo_Keilaniemi,20200101,0,1,Itäkeskus,60/60,317,315.0,2.0,57.8,57.8,64.5
1,118,st101_Espoo_Keilaniemi,20200101,0,2,Länsiväylä,60/60,199,198.0,1.0,68.1,68.1,70.0
2,118,st101_Espoo_Keilaniemi,20200101,1,1,Itäkeskus,60/60,293,289.0,4.0,57.5,57.5,55.5
3,118,st101_Espoo_Keilaniemi,20200101,1,2,Länsiväylä,60/60,220,217.0,3.0,66.5,66.4,72.0
4,118,st101_Espoo_Keilaniemi,20200101,2,1,Itäkeskus,60/60,152,151.0,1.0,57.8,57.9,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56873,118,st101_Espoo_Keilaniemi,20230331,21,2,Länsiväylä,60/60,425,409.0,16.0,69.0,69.1,66.1
56874,118,st101_Espoo_Keilaniemi,20230331,22,1,Itäkeskus,60/60,317,314.0,3.0,61.9,61.9,61.3
56875,118,st101_Espoo_Keilaniemi,20230331,22,2,Länsiväylä,60/60,361,357.0,4.0,70.3,70.2,75.3
56876,118,st101_Espoo_Keilaniemi,20230331,23,1,Itäkeskus,60/60,237,233.0,4.0,62.5,62.5,58.3
56877,118,st101_Espoo_Keilaniemi,20230331,23,2,Länsiväylä,60/60,260,258.0,2.0,71.1,71.0,73.5

In [88]:
dftapiola20_22 = dftapiola20_22.drop(['sijainti','nopeusrajoitus','kaikki', 'raskaat','keskinopeus_kaikki','keskinopeus_raskaat'], axis=1)
dftapiola20_22.rename(columns = {'pistetunnus':'sijainti'},inplace=True)
dftapiola20_22.rename(columns = {'kevyet':'Määrä'},inplace=True)
dftapiola20_22.rename(columns = {'keskinopeus_kevyet':'keskinopeus'},inplace=True)
dftapiola20_22

       sijainti       pvm  klo  suunta suuntaselite  Määrä  keskinopeus
0           118  20200101    0       1    Itäkeskus  315.0         57.8
1           118  20200101    0       2   Länsiväylä  198.0         68.1
2           118  20200101    1       1    Itäkeskus  289.0         57.5
3           118  20200101    1       2   Länsiväylä  217.0         66.4
4           118  20200101    2       1    Itäkeskus  151.0         57.9
...         ...       ...  ...     ...          ...    ...          ...
56873       118  20230331   21       2   Länsiväylä  409.0         69.1
56874       118  20230331   22       1    Itäkeskus  314.0         61.9
56875       118  20230331   22       2   Länsiväylä  357.0         70.2
56876       118  20230331   23       1    Itäkeskus  233.0         62.5
56877       118  20230331   23       2   Länsiväylä  258.0         71.0

[56878 rows x 7 columns]

In [89]:
# Remove all rows with null values
dftapiola20_22.dropna(inplace=True, axis=0)
# Get row count using len() function after removal of null values
row_count = len(dftapiola2)
print(row_count)

dftapiola20_22.head(1)

56876

   sijainti       pvm  klo  suunta suuntaselite  Määrä  keskinopeus
0       118  20200101    0       1    Itäkeskus  315.0         57.8

In [90]:
#muutetaan Määrä sarakkeen data tyyppi float to int
dftapiola20_22['Määrä'] = dftapiola2['Määrä'].astype(int)
dftapiola20_22.dtypes

sijainti          int64
pvm               int64
klo               int64
suunta            int64
suuntaselite     object
Määrä             int32
keskinopeus     float64
dtype: object

In [91]:
#Yhdistetään 2019 ja 20_22 ja tapiola20_22
dfLiikenne = pd.concat([df19, df20_22, dftapiola20_22], ignore_index=True)
dfLiikenne

        sijainti       pvm klo  suunta suuntaselite  Määrä  keskinopeus
0            154  20190101  00       1        Lahti    666          0.0
1            154  20190101  00       2     Helsinki    253          0.0
2            154  20190102  00       1        Lahti    113          0.0
3            154  20190102  00       2     Helsinki     69          0.0
4            154  20190103  00       1        Lahti    130          0.0
...          ...       ...  ..     ...          ...    ...          ...
132253       118  20230331  21       2   Länsiväylä    409         69.1
132254       118  20230331  22       1    Itäkeskus    314         61.9
132255       118  20230331  22       2   Länsiväylä    357         70.2
132256       118  20230331  23       1    Itäkeskus    233         62.5
132257       118  20230331  23       2   Länsiväylä    258         71.0

[132258 rows x 7 columns]

In [95]:
dfLiikenne.to_csv('c:\\apu\\Liikennemaarat_nopeudet_2019_22.csv')

In [93]:
import pyodbc

server = 'localhost'
database = 'FinalProject'
username = 'sa'
password = 'Password1'
cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)


cnxn.execute("Create table FactLiikenne (Liikenne_id int IDENTITY(1,1) Primary Key, sijainti varchar(50), pvm int, klo int, suunta int, suuntaselite varchar(20), maara int, keskinopeus float)") 
cnxn.commit()
cnxn.close()

In [94]:
import pyodbc
server = 'localhost'
database = 'FinalProject'
username = 'sa'
password = 'Password1'
cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()

d = pd.DataFrame(dfLiikenne)

for index, row in d.iterrows():
    cursor.execute("INSERT INTO FactLiikenne values (?,?,?,?,?,?,?)",row['sijainti'],row['pvm'],row['klo'],row['suunta'],row['suuntaselite'],row['Määrä'],row['keskinopeus']) 
cnxn.commit()
cnxn.close()