In [1]:
import pandas as pd

In [116]:
df = pd.read_csv('C:/FinalProject/liikennemaara_h_2019-01-01-2019-12-31.csv',sep =';',encoding= 'utf-8',header = 0)
df

,pistetunnus,sijainti,pvm,suunta,suuntaselite,kaista,jaottelu,ajoneuvoluokka,00_01,01_02,...,15_16,16_17,17_18,18_19,19_20,20_21,21_22,22_23,23_24,yhteensa
0,154,vt4_Viikinmäki,20190101,1,Lahti,*,Ajoneuvoluokka,HA - PA,666,559,...,737,875,702,627,537,592,445,236,151,10356
1,154,vt4_Viikinmäki,20190101,2,Helsinki,*,Ajoneuvoluokka,HA - PA,253,277,...,941,949,877,827,697,525,368,253,161,10515
2,154,vt4_Viikinmäki,20190102,1,Lahti,*,Ajoneuvoluokka,HA - PA,113,66,...,2487,2250,1494,1152,835,723,574,422,192,18212
3,154,vt4_Viikinmäki,20190102,2,Helsinki,*,Ajoneuvoluokka,HA - PA,69,46,...,1174,1256,1075,893,769,659,425,254,170,20162
4,154,vt4_Viikinmäki,20190103,1,Lahti,*,Ajoneuvoluokka,HA - PA,130,118,...,2540,2491,1751,1191,945,879,836,434,174,20349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,154,vt4_Viikinmäki,20191229,2,Helsinki,*,Ajoneuvoluokka,HA - PA,193,133,...,1573,1381,1156,1062,875,653,397,243,153,14185
726,154,vt4_Viikinmäki,20191230,1,Lahti,*,Ajoneuvoluokka,HA - PA,132,114,...,2350,1907,1308,1030,870,748,926,361,205,18336
727,154,vt4_Viikinmäki,20191230,2,Helsinki,*,Ajoneuvoluokka,HA - PA,105,72,...,1275,1282,1308,877,801,638,454,279,158,19650
728,154,vt4_Viikinmäki,20191231,1,Lahti,*,Ajoneuvoluokka,HA - PA,169,113,...,1711,1362,927,735,547,463,456,363,299,15126
729,154,vt4_Viikinmäki,20191231,2,Helsinki,*,Ajoneuvoluokka,HA - PA,118,53,...,1223,1134,940,797,620,554,473,614,699,17512

In [117]:
df = df.drop(['kaista','jaottelu','pistetunnus','ajoneuvoluokka'],axis=1)
df

,sijainti,pvm,suunta,suuntaselite,00_01,01_02,02_03,03_04,04_05,05_06,...,15_16,16_17,17_18,18_19,19_20,20_21,21_22,22_23,23_24,yhteensa
0,vt4_Viikinmäki,20190101,1,Lahti,666,559,352,260,248,262,...,737,875,702,627,537,592,445,236,151,10356
1,vt4_Viikinmäki,20190101,2,Helsinki,253,277,231,202,196,184,...,941,949,877,827,697,525,368,253,161,10515
2,vt4_Viikinmäki,20190102,1,Lahti,113,66,61,38,54,143,...,2487,2250,1494,1152,835,723,574,422,192,18212
3,vt4_Viikinmäki,20190102,2,Helsinki,69,46,59,50,133,582,...,1174,1256,1075,893,769,659,425,254,170,20162
4,vt4_Viikinmäki,20190103,1,Lahti,130,118,78,56,68,156,...,2540,2491,1751,1191,945,879,836,434,174,20349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,vt4_Viikinmäki,20191229,2,Helsinki,193,133,128,110,107,118,...,1573,1381,1156,1062,875,653,397,243,153,14185
726,vt4_Viikinmäki,20191230,1,Lahti,132,114,76,37,80,127,...,2350,1907,1308,1030,870,748,926,361,205,18336
727,vt4_Viikinmäki,20191230,2,Helsinki,105,72,63,56,109,438,...,1275,1282,1308,877,801,638,454,279,158,19650
728,vt4_Viikinmäki,20191231,1,Lahti,169,113,87,63,62,129,...,1711,1362,927,735,547,463,456,363,299,15126
729,vt4_Viikinmäki,20191231,2,Helsinki,118,53,53,60,136,404,...,1223,1134,940,797,620,554,473,614,699,17512

In [118]:
columns = df.columns
tila = columns[0:4]
tila2 = columns[4:-1]

In [121]:
df_unpivot = pd.melt(df, id_vars=tila, value_vars=tila2)

In [122]:
df_unpivot.rename(columns = {'value':'Määrä'},inplace=True)
df_unpivot.rename(columns = {'variable':'Klo'},inplace=True)

In [123]:
df_unpivot[['Klo', 'poisto']] = df_unpivot['Klo'].str.split('_', n=1, expand=True)
df = df_unpivot.drop(['poisto'],axis =1)

In [126]:
df

             sijainti       pvm  suunta suuntaselite Klo  Määrä
0      vt4_Viikinmäki  20190101       1        Lahti  00    666
1      vt4_Viikinmäki  20190101       2     Helsinki  00    253
2      vt4_Viikinmäki  20190102       1        Lahti  00    113
3      vt4_Viikinmäki  20190102       2     Helsinki  00     69
4      vt4_Viikinmäki  20190103       1        Lahti  00    130
...               ...       ...     ...          ...  ..    ...
17515  vt4_Viikinmäki  20191229       2     Helsinki  23    153
17516  vt4_Viikinmäki  20191230       1        Lahti  23    205
17517  vt4_Viikinmäki  20191230       2     Helsinki  23    158
17518  vt4_Viikinmäki  20191231       1        Lahti  23    299
17519  vt4_Viikinmäki  20191231       2     Helsinki  23    699

[17520 rows x 6 columns]